name: Minterop Producer Continuous Integration

on:
  pull_request:

jobs:
  fmt-lint:
    runs-on: ubuntu-22.04
    # TODO: splitting lint/fmt from testing
    name: Test the indexer
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # FIXME: reactivate
      # - name: Rust setup
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: nightly # TODO: back to stable once fmt features are stable
      #     default: true
      #     override: true
      #     components: rustfmt, clippy

      # - name: shftmt setup
      #   uses: mfinelli/setup-shfmt@v1

      # - name: shellcheck setup
      #   uses: mfinelli/setup-shfmt@v1

      # - name: taplo setup
      #   # TODO: use precompiled if available (https://github.com/tamasfe/taplo/issues/326)
      #   # --debug to speed up the install
      #   run: cargo install --debug taplo-cli

      # - name: Prettier setup
      #   run: sudo apt-get install npm && npm install --global prettier

      # - name: Formatting
      #   run: |
      #     cargo +nightly fmt -- --check
      #     shfmt -i 2 -d .
      #     taplo fmt **/*.toml --check
      #     prettier . --check

      # - name: Linting
      #   # TODO: shellcheck (https://github.com/marketplace/actions/shellcheck)
      #   run: |
      #     cargo clippy -- -D warnings

      - name: "Setup AWS Creds"
        run: |
          mkdir ~/.aws
          echo "${{ secrets.AWS_CREDENTIALS }}" > ~/.aws/credentials

      - name: "GCP Auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_TESTNET_KEYS }}"

      - name: "GCR Auth"
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      - name: Smoke tests
        run: |
          touch .env
          scripts/run-tests.sh
