name: Minterop Consumer CICD

on:
  push:
    branches:
      - main

jobs:
  #  Upload the startup script to the storage bucket for deployments to use.
  indexer_startup_script:
    runs-on: ubuntu-22.04
    name: Upload indexer startup script to cloud storage
    steps:
      # Check out code
      - name: Check out code
        uses: actions/checkout@v2

      # Auth to google
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - id: "upload-startup-script"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "./minterop-indexer/indexer-startup.sh"
          destination: "indexer-startup-scripts"


  # Build the indexer docker image (deploy is manual for now)
  build_indexer:
    needs: workspace
    runs-on: ubuntu-22.04
    name: Build indexer image and push image to GCP
    steps:
      # Check out code
      - name: Check out code
        uses: actions/checkout@v2

      # Authenticate/setup gcloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Set up docker auth"
        run: gcloud auth configure-docker

      # Build and push docker image
      - name: "Build Latest Indexer Image and push"
        run: |
          cd minterop-indexer
          docker build \
            -t gcr.io/omni-cloud-1/minterop-indexer:${GITHUB_SHA::6} \
            -t gcr.io/omni-cloud-1/minterop-indexer:latest \
            --build-arg IMAGE=gcr.io/omni-cloud-1/minterop-workspace:${GITHUB_SHA::6} .
          docker push gcr.io/omni-cloud-1/minterop-indexer:${GITHUB_SHA::6}
          docker push gcr.io/omni-cloud-1/minterop-indexer:latest

  # this is a full redeploy! in perspective, this should do DB migratons, and
  # then just start from the current block height
  deploy:
    needs: [build_indexer]
    runs-on: ubuntu-22.04
    name: Deploy and run indexer
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Authenticate/setup gcloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      # get secrets from GH
      # TODO: currently a problem for CD: this defines the block height
      # -> only good for redeploy + sandbox
      - name: Redeployment script
        # TODO: use commit hash again
        run: |
          echo "${{ secrets.SANDBOX_ENV }}" > sandbox.env
          scripts/redeploy.sh sandbox latest
        # run: |
        #   echo "${{ secrets.SANDBOX_ENV }}" > sandbox.env
        #   scripts/redeploy.sh sandbox ${GITHUB_SHA::6}
